### ISSUE TITLE
这里不会写错了吗？$|a|^2 + |b|^2 + |c|^2+ |d|^2 = 1$

### ISSUE THREAD

**Issue by TrafficTse** [MicrosoftDocs/quantum-docs-pr.zh-CN#3]
应该是$|ac|^2 + |ad|^2 + |bc|^2+ |bd|^2 = 1$吧？🤔

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: feb830cc-7d9b-c13e-4652-115352ea1e29
* Version Independent ID: f9484b57-1dc8-06a9-ac6d-cdc7c4769981
* Content: [用于量子计算的线性代数 - Microsoft Quantum](https://docs.microsoft.com/zh-cn/quantum/overview/algebra-for-quantum-computing)
* Content Source: [articles/overview/algebra-for-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr.zh-cn/blob/live/articles/overview/algebra-for-quantum-computing.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by srvbpigh** [comment]
Hello, @TrafficTse
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@TrafficTse
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by V-vafune** [comment]
你好，@TrafficTse， 

我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by TrafficTse** [comment]
https://docs.microsoft.com/zh-cn/quantum/overview/algebra-for-quantum-computing
我刚才查看了这个页面，发现你们已经改正过来了，谢谢🤣🤣🤣
