### ISSUE TITLE
Latex not work

### ISSUE THREAD

**Issue by ianahao** [MicrosoftDocs/quantum-docs-pr.zh-CN#4]
$$ \begin{bmatrix} a \\ b \end{bmatrix} \otimes \begin{bmatrix} c \\ d \end{bmatrix} =\begin{bmatrix} a \begin{bmatrix} c \\ d \end{bmatrix} \\ b \begin{bmatrix}c \\ d \end{bmatrix} \end{bmatrix} = \begin{bmatrix} ac \\ ad \\ bc \\ bd \end{bmatrix}. $$

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: feb830cc-7d9b-c13e-4652-115352ea1e29
* Version Independent ID: f9484b57-1dc8-06a9-ac6d-cdc7c4769981
* Content: [用于量子计算的线性代数 - Microsoft Quantum](https://docs.microsoft.com/zh-cn/quantum/overview/algebra-for-quantum-computing)
* Content Source: [articles/overview/algebra-for-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr.zh-cn/blob/live/articles/overview/algebra-for-quantum-computing.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by srvbpigh** [comment]
Hello, @ianahao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ianahao
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by Bradben** [comment]
Hi - 
This is a known issue that came to our attention recently, and the quantum docs team is working on a fix. (The machine translation is stripping some characters that affect some of the LaTeX rendering.) We hope to find out this week if the solution that we're testing works.

Thanks,
Brad

**Comment by CeciAc** [comment]
Assigned to the owner as per comment below about being a source issue

**Comment by ishasahni1** [comment]
@ianahao this is a source issue, once it is addressed, the file will be localized and reflect new changes.
